// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewData;

namespace ReviewData.Migrations
{
    [DbContext(typeof(ReviewDb))]
    partial class ReviewDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reviews")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ReviewData.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerAuthId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerAuthId = "f756701c-4336-47b1-8317-a16e84bd0059",
                            CustomerName = "Chris Burrell"
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerAuthId = "07dc5dfc-9dad-408c-ba81-ff6a8dd3aec2",
                            CustomerName = "Paul Mitchell"
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerAuthId = "1e3998f7-4ca6-42e0-9c78-8cb030f65f47",
                            CustomerName = "Jack Ferguson"
                        },
                        new
                        {
                            CustomerId = 4,
                            CustomerAuthId = "bce3bb9c-5947-4265-8a7d-8588655bbabe",
                            CustomerName = "Carter Ridgeway"
                        },
                        new
                        {
                            CustomerId = 5,
                            CustomerAuthId = "fb9e3941-6830-4387-be15-eeac14848c01",
                            CustomerName = "Karl Hall"
                        });
                });

            modelBuilder.Entity("ReviewData.Purchase", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "ProductId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CustomerId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CustomerId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CustomerId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            CustomerId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            CustomerId = 3,
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("ReviewData.Review", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId", "ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            ProductId = 1,
                            Rating = 3,
                            ReviewText = "Good",
                            TimeStamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Visible = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
